// Cross-check the C++ control port against the Python reference vectors.
// reference_control.csv is generated by scripts/gen_reference.py from
// colav_automaton (the source of truth); each row is recomputed here and
// must match. This is the verification artifact for the C++ twin.
#include "colav_cpp/control.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {

std::vector<double> parse_row(const std::string& line) {
  std::vector<double> cols;
  std::stringstream ss(line);
  std::string cell;
  while (std::getline(ss, cell, ',')) {
    cols.push_back(std::stod(cell));
  }
  return cols;
}

}  // namespace

TEST(ControlCrossCheck, MatchesPythonReference) {
  std::ifstream f(REFERENCE_CSV);
  ASSERT_TRUE(f.is_open()) << "cannot open " << REFERENCE_CSV;

  std::string line;
  std::getline(f, line);  // header

  int rows = 0;
  int exact = 0;
  double max_u_diff = 0.0;
  while (std::getline(f, line)) {
    if (line.empty()) continue;
    const auto c = parse_row(line);
    ASSERT_EQ(c.size(), 16u) << "malformed row " << rows;

    // columns: t x y psi xw yw a v eta tp v1x v1y delta u_py l1_py l2_py
    const double u = colav::prescribed_time_control(
        c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7], c[8], c[9]);
    const double diff = std::fabs(u - c[13]);
    max_u_diff = std::max(max_u_diff, diff);
    if (u == c[13]) ++exact;
    EXPECT_NEAR(u, c[13], 1e-9) << "u mismatch, row " << rows;

    const bool l1 = colav::l1_check(c[1], c[2], c[10], c[11], c[12]);
    const bool l2 = colav::l2_check(c[1], c[2], c[3], c[10], c[11]);
    EXPECT_EQ(l1, c[14] != 0.0) << "L1 mismatch, row " << rows;
    EXPECT_EQ(l2, c[15] != 0.0) << "L2 mismatch, row " << rows;

    ++rows;
  }

  EXPECT_GT(rows, 0);
  std::cout << "[cross-check] rows=" << rows
            << "  bit-exact u=" << exact << "/" << rows
            << "  max|u-u_py|=" << max_u_diff << std::endl;
}
