// Cross-check the C++ risk-index port against the Python reference vectors
// (generated by scripts/gen_reference.py from compute_risk_index / G22_check,
// which use colav_unsafe_set's calc_cpa). Python is the source of truth.
#include "colav_cpp/risk.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {

std::vector<double> parse_row(const std::string& line) {
  std::vector<double> cols;
  std::stringstream ss(line);
  std::string cell;
  while (std::getline(ss, cell, ',')) cols.push_back(std::stod(cell));
  return cols;
}

}  // namespace

TEST(RiskCrossCheck, MatchesPythonReference) {
  std::ifstream f(REFERENCE_RISK);
  ASSERT_TRUE(f.is_open()) << "cannot open " << REFERENCE_RISK;

  std::string line;
  std::getline(f, line);  // header

  int rows = 0;
  int exact = 0;
  double max_diff = 0.0;
  while (std::getline(f, line)) {
    if (line.empty()) continue;
    const auto c = parse_row(line);
    ASSERT_EQ(c.size(), 11u) << "malformed row " << rows;

    // columns: px py psi v ox oy ov opsi K ri_py g22_py
    const std::vector<colav::Obstacle> obs = {{c[4], c[5], c[6], c[7]}};

    const double ri = colav::compute_risk_index(c[0], c[1], c[2], obs, c[3]);
    const double diff = std::fabs(ri - c[9]);
    max_diff = std::max(max_diff, diff);
    if (ri == c[9]) ++exact;
    EXPECT_NEAR(ri, c[9], 1e-12) << "ri mismatch, row " << rows;

    const bool g22 = colav::g22_check(c[0], c[1], c[2], obs, c[3], c[8]);
    EXPECT_EQ(g22, c[10] != 0.0) << "g22 mismatch, row " << rows;

    ++rows;
  }

  EXPECT_GT(rows, 0);
  std::cout << "[risk cross-check] rows=" << rows
            << "  bit-exact ri=" << exact << "/" << rows
            << "  max|ri-ri_py|=" << max_diff << std::endl;
}
